name: Docker Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract repository name
      id: repo_name
      run: echo "::set-output name=name::${GITHUB_REPOSITORY##*/}"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.name }}:latest

    - name: Get short SHA
      id: get_sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Create GitHub Release
      if: success()
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        VERSION="1.0.0+${{ steps.get_sha.outputs.sha }}"
        gh release create $VERSION \
          --title "Release $VERSION" \
          --notes "Auto-generated release from GitHub Actions."
